application: task-keeper
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets

- url: /jquery-ui
  static_dir: jquery-ui

- url: /.*
  script: main.py
